#!/usr/bin/env python3
import sys, os

def traverse(src: str, dest: str):
    if os.path.isfile(src):
        print(f'{src} -> {dest}')
        try:
            os.link(src, dest)
        except Exception as e:
            print(f"Error linking {src} to {dest}: {e}")
    else:
        if not os.path.exists(dest):
            os.mkdir(dest)
        items = os.listdir(src)
        
        for item in items:
            src_path = os.path.join(src, item)
            dest_path = os.path.join(dest, item)
            traverse(src_path, dest_path)


def main(src: str, dest: str):
    src = os.path.expanduser(os.path.abspath(src))
    dest = os.path.expanduser(os.path.abspath(dest))

    for i in (src, dest):
        if not os.path.exists(i):
            print(f"{i} directory does not exists")
            sys.exit(1)
        
        elif os.path.isfile(i):
            print(f"{i} must be a directory")
            sys.exit(1)

    traverse(src, dest)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: linkdir [source] [dest]")
        sys.exit(1)

    src = sys.argv[1]
    dest = sys.argv[2]

    main(src, dest)