#!/usr/bin/env python3

import random, os
from colorama import Fore

cows = "beavis.zen blowfish bong bud-frogs bunny cheese cower daemon default dragon dragon-and-cow elephant eyes flaming-sheep ghostbusters head-in hellokitty kiss kitty koala kosh luke-koala meow milk moofasa moose mutilated ren satanic sheep skeleton small sodomized stegosaurus stimpy three-eyes turkey turtle tux udder vader-koala www".split()

print(Fore.BLUE)
os.system(f"fortune | cowsay -f {cows[random.randint(0, len(cows)-1)]}")
print(Fore.RESET + '\n')